# -*- coding: utf-8 -*-
"""test.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17eCGgzMXhuJYKullValVJodm2ypXzk2F
"""

# Initialize the sum to 0
total_sum = 0

# Loop through numbers from 1 to 10
for number in range(1, 11):
    total_sum += number  # Add each number to the total sum

# Print the result
print("The sum of numbers from 1 to 10 is:", total_sum)